service:
  name: go-simple-svc
  debug: false
  timezone: "Asia/Jakarta"

server:
  host: "localhost"
  port: "8080"
  write_timeout: 10 # in second
  read_timeout: 10 # in second
  shutdown_timeout: 5 # in second

database:
  host: "localhost"
  port: "27017"
  name: "message"
  collection: "message_collection"
  timeout: 5 # in second